import { writeFile } from 'node:fs/promises';
import { renderADR } from '../adr/render.js';
import { activeProvider, modelFor } from '../llm/index.js';
import type { Architecture } from '../types/architecture.js';
import { LAYER_ORDER } from '../types/architecture.js';
import type { ProjectProfile } from '../types/profile.js';
import type { ValidationResult } from '../types/validation.js';
import { ensureDir, outputPath, timestampSlug } from '../utils/paths.js';

export interface DocumentInputs {
  profile: ProjectProfile;
  architecture: Architecture;
  validation: ValidationResult[];
  mermaid: string;
}

export interface DocumentOutput {
  path: string;
  contents: string;
}

const FLAG_LABELS: Record<string, string> = {
  deprecated: 'Deprecated',
  'stale-release': 'Stale release',
  'peer-dep-conflict': 'Peer dep conflict',
  prerelease: 'Pre-release',
  'not-found': 'Not on npm',
  'fetch-failed': 'Lookup failed',
};

function confidenceBadge(score: number): string {
  if (score >= 85) return `${score}% ✅`;
  if (score >= 65) return `${score}% ⚠️`;
  return `${score}% ❌`;
}

function complexityBadge(c: string): string {
  return c.charAt(0).toUpperCase() + c.slice(1);
}

export function buildMarkdown(inputs: DocumentInputs): string {
  const { profile, architecture, validation, mermaid } = inputs;
  const now = new Date();
  const validationByLayer = new Map<string, ValidationResult>();
  for (const v of validation) validationByLayer.set(v.layer, v);

  const sections: string[] = [];

  sections.push(`# ${profile.projectName} — Architecture Plan`);
  sections.push('');
  sections.push(
    `> Generated by **Architect-AI** on ${now.toISOString()} · mode: \`${profile.mode}\` · provider: \`${activeProvider()}\` · architecture model: \`${modelFor('architecture')}\``,
  );
  sections.push('');

  sections.push('## 1. Project Overview');
  sections.push('');
  sections.push(profile.summary);
  sections.push('');
  sections.push('| Attribute | Value |');
  sections.push('| --- | --- |');
  sections.push(`| Project type | ${profile.projectType} |`);
  sections.push(`| Expected scale | ${profile.expectedScale} |`);
  sections.push(`| Expected load | ${profile.expectedLoad} |`);
  sections.push(`| Deployment preference | ${profile.deploymentPreference} |`);
  sections.push(`| Auth needs | ${profile.authNeeds} |`);
  sections.push(`| AI requirements | ${profile.aiRequirements} |`);
  sections.push(`| Budget sensitivity | ${profile.budgetSensitivity} |`);
  sections.push(`| Timeline | ${profile.timeline} |`);
  sections.push('');

  sections.push('## 2. Recommended Stack');
  sections.push('');
  sections.push('| Layer | Technology | Maturity | Confidence | Latest |');
  sections.push('| --- | --- | --- | --- | --- |');
  for (const layerKey of LAYER_ORDER) {
    const rec = architecture.layers[layerKey];
    const v = validationByLayer.get(layerKey);
    const latest = v?.latestVersion ? `\`${v.latestVersion}\`` : '—';
    sections.push(
      `| ${layerKey} | ${rec.name} | ${rec.maturity} | ${confidenceBadge(rec.confidence)} | ${latest} |`,
    );
  }
  sections.push('');

  sections.push('## 3. Per-Layer Detail');
  sections.push('');
  for (const layerKey of LAYER_ORDER) {
    const rec = architecture.layers[layerKey];
    sections.push(`### ${layerKey} — ${rec.name}`);
    sections.push('');
    sections.push(`**Rationale:** ${rec.rationale}`);
    sections.push('');
    sections.push('**Benefits:**');
    for (const b of rec.benefits) sections.push(`- ${b}`);
    sections.push('');
    sections.push('**Tradeoffs:**');
    for (const t of rec.tradeoffs) sections.push(`- ${t}`);
    sections.push('');
  }

  sections.push('## 4. Architecture Decision Records');
  sections.push('');
  for (const adr of architecture.adrs) {
    sections.push(renderADR(adr));
    sections.push('');
  }

  sections.push('## 5. System Architecture Diagram');
  sections.push('');
  sections.push('```mermaid');
  sections.push(mermaid);
  sections.push('```');
  sections.push('');

  sections.push('## 6. Compatibility Validation Report');
  sections.push('');
  const flagged = validation.filter((v) => v.flags.length > 0);
  if (flagged.length === 0) {
    sections.push('All recommended packages passed deterministic validation against the npm registry.');
  } else {
    sections.push('| Layer | Package | Flags | Notes |');
    sections.push('| --- | --- | --- | --- |');
    for (const v of flagged) {
      const flags = v.flags.map((f) => FLAG_LABELS[f] ?? f).join(', ');
      const notes = [
        v.deprecationMessage,
        ...v.notes,
        ...v.peerDepConflicts.map((c) => `Peer: ${c}`),
      ]
        .filter(Boolean)
        .join(' · ') || '—';
      sections.push(
        `| ${v.layer} | \`${v.npmPackage ?? v.technology}\` | ${flags} | ${notes} |`,
      );
    }
  }
  sections.push('');

  sections.push('## 7. Estimations');
  sections.push('');
  sections.push('| Estimate | Value |');
  sections.push('| --- | --- |');
  sections.push(`| MVP duration | ${architecture.estimations.mvpDuration} |`);
  sections.push(`| Team size | ${architecture.estimations.teamSize} |`);
  sections.push(`| Monthly infra cost | ${architecture.estimations.monthlyInfraCostUsd} |`);
  sections.push(`| Complexity | ${complexityBadge(architecture.estimations.complexity)} |`);
  sections.push(`| Scalability tier | ${architecture.estimations.scalabilityTier} |`);
  sections.push('');

  sections.push('---');
  sections.push(
    `_Document validated against the npm registry. Validation does not guarantee runtime compatibility — review per-layer flags above before adopting._`,
  );

  return sections.join('\n');
}

export async function writeDocument(inputs: DocumentInputs): Promise<DocumentOutput> {
  const contents = buildMarkdown(inputs);
  const path = outputPath(timestampSlug(), inputs.profile.projectName);
  await ensureDir(path);
  await writeFile(path, contents, 'utf8');
  return { path, contents };
}